const mongoose = require("mongoose");
const validator = require('validator'); // schema levelvalidation

const userSchema = new mongoose.Schema({

    firstName:{
        type: String,
        minlength: 2,
        maxlength: 50,
        required: true,
    },
    lastName: {
            type: String,
            minlength: 2,
            maxlength: 50,
            required: true,
        },
        emailId: {
            type: String,
            required: true,
            unique: true,
            lowercase: true,
            trim: true,
            validate(value) {
                if (!validator.isEmail(value)) {
                    throw new Error("Invalid email format" + value);
                }
            }
        },
        password: {
            type: String,
            required: true,
            validate(value){
                if(!validator.isStrongPassword(value, {
                    minLength: 8,
                    minLowercase: 1,
                    minUppercase: 1,
                    minNumbers: 1,
                    minSymbols: 1
                })) {
                    throw new Error("Password must be strong");
                }
            }
        },
        age: {
            type: Number,
            min:18,
            required: true,
        },
        photoUrl: {
          type:String,
            required: true,
            default: "https://example.com/default-profile.png",
            validate(value) {
                if (!validator.isURL(value)) {
                    throw new Error("Invalid URL format" + value);
                }
            }
        },
        skills: {
            type: [String]
        },
        gender:{
            type: String,
            validate(value){
                if(!["male", "female", "other"].includes(value)){
                    throw new Error("invalid gender type")
                }
            }
        }

    }
)
const User = mongoose.model("User", userSchema);

module.exports = User;
// This code defines a Mongoose schema and model for a User in a MongoDB database
// _id is a unique string and automatically generated by MongoDB
