const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({

    firstName:{
        type: String
    },
    lastName: {
            type: String
        },
        emailId: {
            type: String
        },
        password: {
            type: String
        }
    }
)
const User = mongoose.model("User", userSchema);

module.exports = User;
// This code defines a Mongoose schema and model for a User in a MongoDB database
// _id is a unique string and automatically generated by MongoDB
